allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')

    tasks.withType(
        org.jetbrains.kotlin.gradle.tasks.KotlinCompile
    ).configureEach { kotlinTask ->

        if (project.name == 'flutter_custom_tabs_android') {
            kotlinTask.kotlinOptions.jvmTarget = '1.8'
        } else if (project.name == 'flutter_statusbarcolor_ns') {
            kotlinTask.kotlinOptions.jvmTarget = '1.8'
        } else if (project.name == 'flutter_web_auth_2') {
            kotlinTask.kotlinOptions.jvmTarget = '11'
        } else if (project.name == 'google_maps_flutter_android') {
            kotlinTask.kotlinOptions.jvmTarget = '17'
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}